config/routes.rb
Rails.application.routes.draw do
  root "users#index"
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :restaurants do
    resources :reviews, shallow: true
  end

  resources :sessions, only: [:new, :create, :destroy]
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews

  validates :rstrnt_name, presence: true
  validates :address, presence: true
  validates :phone_num, presence: true
  validates :hours, presence: true
  validates :rstrnt_site, presence: true

  def avg_food
    # self.reviews.each {|review| review.food_rating }
  end

  def avg_service
    # self.reviews.each {|review| review.service_rating }
  end

  def avg_ambiance
    # self.reviews.each {|review| review.ambiance_rating }
  end

  def food_rating_icons
    self.food_rating ||= 0
    raw(("<i class='glyphicon glyphicon-star'></i> " * self.food_rating) + ("<i class='glyphicon glyphicon-star-empty'></i> " * (5-self.food_rating)).strip)
  end

  def service_rating_icons
    self.service_rating ||= 0
    raw(("<i class='glyphicon glyphicon-star'></i> " * self.service_rating) + ("<i class='glyphicon glyphicon-star-empty'></i> " * (5-self.service_rating)).strip)
  end

  def ambiance_rating_icons
    self.ambiance_rating ||= 0
    raw(("<i class='glyphicon glyphicon-star'></i> " * self.ambiance_rating) + ("<i class='glyphicon glyphicon-star-empty'></i> " * (5-self.ambiance_rating)).strip)
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :user

  validates :food_rating, presence: true
  validates :service_rating, presence: true
  validates :ambiance_rating, presence: true
  validates :review_content, presence: true

  include ActionView::Helpers::OutputSafetyHelper

  def food_rating_icons
    self.food_rating ||= 0
    raw(("<i class='glyphicon glyphicon-star'></i> " * self.food_rating) + ("<i class='glyphicon glyphicon-star-empty'></i> " * (5-self.food_rating)).strip)
  end

  def service_rating_icons
    self.service_rating ||= 0
    raw(("<i class='glyphicon glyphicon-star'></i> " * self.service_rating) + ("<i class='glyphicon glyphicon-star-empty'></i> " * (5-self.service_rating)).strip)
  end

  def ambiance_rating_icons
    self.ambiance_rating ||= 0
    raw(("<i class='glyphicon glyphicon-star'></i> " * self.ambiance_rating) + ("<i class='glyphicon glyphicon-star-empty'></i> " * (5-self.ambiance_rating)).strip)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews

  has_secure_password
  validates :email, presence: true, uniqueness: true, length: { minimum: 5 }

  def food_rating_icons
    self.food_rating ||= 0
    raw(("<i class='glyphicon glyphicon-star'></i> " * self.food_rating) + ("<i class='glyphicon glyphicon-star-empty'></i> " * (5-self.food_rating)).strip)
  end

  def service_rating_icons
    self.service_rating ||= 0
    raw(("<i class='glyphicon glyphicon-star'></i> " * self.service_rating) + ("<i class='glyphicon glyphicon-star-empty'></i> " * (5-self.service_rating)).strip)
  end

  def ambiance_rating_icons
    self.ambiance_rating ||= 0
    raw(("<i class='glyphicon glyphicon-star'></i> " * self.ambiance_rating) + ("<i class='glyphicon glyphicon-star-empty'></i> " * (5-self.ambiance_rating)).strip)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private

    helper_method :current_user
    helper_method :current_rest
    helper_method :current_review

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def current_rest
      @current_rest ||= Restaurant.find(session[:restaurant_id]) if session[:restaurant_id]
    end

    def current_review
      @current_review ||= Review.find(session[:review_id]) if session[:review_id]
    end

    def authorize
      redirect_to login_path, alert: 'Not authorized - You must be logged in!' if current_user.nil?
    end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :authorize, only: [:edit, :update, :destroy]

  def index
    if params[:restaurant_id]
      restaurant = Restaurant.find(params[:restaurant_id])
      redirect_to restaurant_path(restaurant)
    end
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      session[:restaurant_id] = @restaurant.id
      flash[:notice] = "You have successfully signed up!"
      redirect_to current_rest
    else
      render 'new'
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update_attributes(params.require(:restaurant).permit(
    :id,
    :rstrnt_name,
    :phone_num,
    :address,
    :hours,
    :rstrnt_site
    ))
      redirect_to restaurant_path
    else
      render :edit
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.reviews.destroy_all
    @restaurant.destroy
    redirect_to root_path
  end

private

  def restaurant_params
      params.require(:restaurant).permit(:rstrnt_name, :phone_num, :address, :hours, :rstrnt_site)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    before_action :authorize, only: [:edit, :update, :destroy]

    def index
      @reviews = Review.all
    end

    def show
      @review = Review.find(params[:id])
    end

    def new
      @restaurant = Restaurant.find(params[:restaurant_id])
      @review = Review.new
    end

    def create
      @review = Review.new(review_params)
      @review.restaurant_id = params[:restaurant_id]
      @review.user = current_user
      if @review.save
        session[:review_id] = @review.id
        flash[:notice] = "You have successfully signed up!"
        redirect_to restaurant_path(@review.restaurant)
      else
        render 'new'
      end
    end

    def edit
      @review = Review.find(params[:id])
    end

    def update
      @review = Review.find(params[:id])
      if @review.update_attributes(params.require(:review).permit(
      :id,
      :food_rating,
      :service_rating,
      :ambiance_rating,
      :review_content,
      :user_name
      ))
        redirect_to restaurant_path(@review.restaurant)
      else
        render :edit
      end
    end

    def destroy
      @review = Review.find(params[:id])
      @review.destroy
      redirect_to restaurant_path(@review.restaurant)
    end

  private

    def review_params
        params.require(:review).permit(:food_rating, :service_rating, :ambiance_rating, :review_content)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in!'
    else
      flash.now.alert = 'Invalid login credentials - Try again!'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorize, only: [:edit, :update]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "You have successfully signed up!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params.require(:user).permit(
    :id,
    :user_name,
    :num_reviews,
    :about_me
    ))
      redirect_to current_user
    else
      render :edit
    end
  end

private

  def user_params
      params.require(:user).permit(:user_name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>U - V I E W</title>
  <link rel="icon" type="ico" href="uview.ico">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
</head>
<body>
  <ul class="nav nav-pills">

    <div class="div1">
      <li role="presentation" class="logo"><a href="/">U - V I E W</a></li>
    </div>

    <div class="div2">
    <div class="div3">
      <% if current_user %>
          <li role="presentation" class="navbar-text navbar-right">
            <%= link_to '.Logout', session_path('dummy'), method: :delete %>
          </li>
          <li role="presentation" class="navbar-text navbar-right">
            <%= link_to "." + current_user.user_name, current_user %>
          </li>
      <% else %>
          <li role="presentation" class="navbar-text navbar-right">
            <%= link_to '.Sign Up', new_user_path %>
          </li>
          <li role="presentation" class="navbar-text navbar-right">
            <%= link_to '.Login', login_path %>
          </li>
      <% end %>
    </div>

    <div class="div4">
      <li role="presentation">
        <%= form_tag restaurants_path, method: :get, class: "form-inline" do %>
          <%= collection_select("", :restaurant_id, Restaurant.all, :id, :rstrnt_name, {prompt: "Restaurant"}, { class: "form-control", id: "restaurant-search" }) %>
          <%= submit_tag "Go!", disabled: true, id: "search-submit", class: "btn btn-primary" %>
        <% end %>

        <script>
        $(document).ready(function() {
          $("#restaurant-search").on("change", function(evt) {
            if (evt.target.value != "") {
              $("#search-submit").attr("disabled", false);
            } else {
              $("#search-submit").attr("disabled", true);
            }
          });
        });
        </script>
      </li>
    </div>
    </div>
</ul>

  <%= yield %>
</body>
</html>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant Info</h1>
<%= form_for @restaurant do |f| %>
  <% if @restaurant.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @restaurant.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label "Restaurant Name" %>
    <%= f.text_field :rstrnt_name %>
  </div>
  <div class="field">
    <%= f.label "Address" %>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label "Phone Number" %>
    <%= f.text_field :phone_num %>
  </div>
  <div class="field">
    <%= f.label "Hours" %>
    <%= f.text_field :hours %>
  </div>
  <div class="field">
    <%= f.label "Website" %>
    <%= f.text_field :rstrnt_site %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/restaurants/index.html.erb
<h1>RESTAURANTS</h1>
<br>

<% @restaurants.each do |restaurant| %>
    <p><%= restaurant.rstrnt_name %></p>
    <p><%= "Phone Number: #{restaurant.phone_num}" %></p>
    <p><%= "Address: #{restaurant.address}" %></p>
    <p><%= "Hours: #{restaurant.hours}" %></p>
    <p>Website: <a href="https://<%= restaurant.rstrnt_site %>"><%= "#{restaurant.rstrnt_site}" %></a></p>
    <p>Reviews:</p>
    <br>
    <br>
    <br>
<% end %>

<h2><%= link_to "Add New Restaurant", new_restaurant_path %></h2>

app/views/restaurants/new.html.erb
<h1>Register your Restaurant</h1>
<%= form_for @restaurant do |f| %>
  <% if @restaurant.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @restaurant.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %><br>
  <div class="field">
    <%= f.label "Restaurant Name:" %>
    <%= f.text_field :rstrnt_name %>
  </div><br>
  <div class="field">
    <%= f.label "Address:" %>
    <%= f.text_field :address %>
  </div><br>
  <div class="field">
    <%= f.label "Phone Number:" %>
    <%= f.text_field :phone_num %>
  </div><br>
  <div class="field">
    <%= f.label "Hours:" %>
    <%= f.text_field :hours %>
  </div><br>
  <div class="field">
    <%= f.label "Website:" %>
    <%= f.text_field :rstrnt_site %>
  </div><br>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/restaurants/show.html.erb
<main class="profile">

  <h2 class="rstname">
    <%= @restaurant.rstrnt_name %>
    &nbsp;
    <small class="edit">
      <%= link_to "Review This Restaurant!", new_restaurant_review_path(@restaurant) %>
    </small>
  </h2>
  <p class="profattr"><%= "Phone Number: #{@restaurant.phone_num}" %></p>
  <p class="profattr"><%= "Address: #{@restaurant.address}" %></p>
  <p class="profattr"><%= "Hours: #{@restaurant.hours}" %></p>
  <p class="profattr">Website: <a href="https://<%= @restaurant.rstrnt_site %>"><%= "#{@restaurant.rstrnt_site}" %></a></p>
  <p class="edel"><%= link_to "Edit Restaurant Info", edit_restaurant_path %></p>
  <!-- <p class="edel"><%= link_to "Delete Restaurant", restaurant_path, method: :delete, data: { confirm: "Are you sure?" } %></p> -->
  <p class="profattr">Reviews:</p>

  <div class="userrev">
    <% @restaurant.reviews.each do |review| %>
      <div class="rev">
        <p class="profrev">
          <strong>
            <%= link_to review.user.user_name, user_path(review.user) %>
            <% if current_user == review.user %>
              &nbsp;|&nbsp;
              <%= link_to "Delete Review", review_path(review), method: :delete, data: { confirm: "Are you sure?" } %>
              &nbsp;|&nbsp;
              <%= link_to "Edit Review", edit_review_path(review) %>
            <% end %>
          </strong>
        </p>
        <p><%= review.food_rating_icons %></p>
        <p><%= review.service_rating_icons %></p>
        <p><%= review.ambiance_rating_icons %></p>
        <p style="width: 700px; word-wrap:break-word;"><%= review.review_content %></p>
      </div>
      <br>
    <% end %>
  </div>

</main>

app/views/reviews/edit.html.erb
<h1 class="formhead">- EDIT REVIEW -</h1>

  <%= form_for([@restaurant, @review]) do |f| %>
    <div class="field">
      <%= f.label "Food Rating" %>
      <%= f.text_field :food_rating, placeholder: "Rate 1 - 5", style: "font-family: Helvetica Neue" %>
    </div>
    <div class="field">
      <%= f.label "Service Rating" %>
      <%= f.text_field :service_rating, placeholder: "Rate 1 - 5", style: "font-family: Helvetica Neue" %>
    </div>
    <div class="field">
      <%= f.label "Ambiance Rating" %>
      <%= f.text_field :ambiance_rating, placeholder: "Rate 1 - 5", style: "font-family: Helvetica Neue" %>
    </div>
    <div class="field">
      <%= f.label "Comment" %>
      <%= f.text_area :review_content %>
    </div>
    <div class="actions"><%= f.submit %></div>
  <% end %>

app/views/reviews/index.html.erb
<h1>REVIEWS</h1>
<br>

<% @reviews.each do |review| %>

    <p><strong>Food Rating:</strong>
      <span class="rating-stars">
        <%= review.food_rating_icons %>
      </span>
    </p>
    <p><strong>Service Rating:</strong>
      <span class="rating-stars">
        <%= review.service_rating_icons %>
      </span>
    </p>
    <p><strong>Ambiance Rating:</strong>
      <span class="rating-stars">
        <%= review.ambiance_rating_icons %>
      </span>
    </p>
    <p><strong>Comment:</strong></p>
    <%= review.review_content %>
    <br>

<% end %>

app/views/reviews/new.html.erb
<h1 class="formhead">- New Review -</h1>

  <%= form_for([@restaurant, @review]) do |f| %>
    <div class="field">
      <%= f.label "Food Rating:" %>
      <%= f.text_field :food_rating, placeholder: "Rate 1 - 5", style: "font-family: Helvetica Neue" %>
    </div><br>
    <div class="field">
      <%= f.label "Service Rating:" %>
      <%= f.text_field :service_rating, placeholder: "Rate 1 - 5", style: "font-family: Helvetica Neue" %>
    </div><br>
    <div class="field">
      <%= f.label "Ambiance Rating:" %>
      <%= f.text_field :ambiance_rating, placeholder: "Rate 1 - 5", style: "font-family: Helvetica Neue" %>
    </div><br>
    <div class="field">
      <%= f.label "Comment:" %><br>
      <%= f.text_area :review_content %>
    </div><br>
    <div class="actions"><%= f.submit %></div>
  <% end %>

app/views/users/edit.html.erb
<h1 class="formhead">- Edit Profile -</h1>
<%= form_for current_user do |f| %>
  <% if current_user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in current_user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label "Name:" %>
    <%= f.text_field :user_name %>
  </div><br>
  <div class="field">
    <%= f.label "Number of Reviews:" %><br>
    <%= f.text_field :num_reviews %>
  </div><br>
  <div class="field">
    <%= f.label "About Me:" %><br>
    <%= f.text_area :about_me %>
  </div><br>

  <div class="actions butt"><%= f.submit "Submit " %></div>
<% end %>

app/views/users/index.html.erb
<main>
  <img class="bg" src="homebg.png" alt="HomeBG">
</main>

app/views/users/new.html.erb
<h1 class="formhead">- Sign Up -</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label "Name:" %>
    <%= f.text_field :user_name %>
  </div><br>
  <div class="field">
    <%= f.label "Email:" %>
    <%= f.text_field :email %>
  </div><br>
  <div class="field">
    <%= f.label "Password:" %>
    <%= f.password_field :password %>
  </div><br>
  <div class="field">
    <%= f.label "Confirm Password:" %>
    <%= f.password_field :password_confirmation %>
  </div><br>
  <div class="actions butt"><%= f.submit "Sign Up " %></div>
<% end %>

app/views/users/show.html.erb
<main class="profile">
    <div class="prof pic"><%= link_to "https://goo.gl/QirYt5" do %>
        <%= gravatar_image_tag(@user.email, :alt => @user.user_name, width: 10) %>
        <br>
        <span><small>Change Gravatar</small></span>
        <% end %>
    </div>
    <div class="prof">
        <div class="profname">
            <%= @user.user_name %>
            &nbsp;
            <small class="edit">
                <% if current_user == @user %>
                    <%= link_to "Edit Profile", edit_user_path %>
                    &nbsp; | &nbsp;
                    <%= link_to "Register Restaurant", new_restaurant_path %>
                <% end %>
            </small>
        </div>
        <div class="numrev">
            <%= "Number of Reviews: #{@user.num_reviews}" %>
        </div>
    </div>
    <br>
    <br>
    <p class="profattr">About Me:</p>
    <p class="about" style="width: 700px; word-wrap:break-word;"><%= "#{@user.about_me}" %></p>
    <br>
    <p class="profattr">Reviews:</p>

    <div class="userrev">
        <% @user.reviews.each do |review|%>
            <div class="rev">
                <div class="profrev">
                    <strong>
                        <%= link_to review.restaurant.rstrnt_name, restaurant_path(review.restaurant) %>
                        <% if current_user == @user %>
                            &nbsp;|&nbsp;
                            <%= link_to "Delete Review", review_path(review), method: :delete, data: { confirm: "Are you sure?" } %>
                            &nbsp;|&nbsp;
                            <%= link_to "Edit Review", edit_review_path(review) %>
                        <% end %>
                    </strong>
                </div>

                <%= review.food_rating_icons %> Food
                <br>
                <%= review.service_rating_icons %> Service
                <br>
                <%= review.ambiance_rating_icons %> Ambiance
                <br>
                <p style="width: 700px; word-wrap:break-word;"><%= review.review_content %></p>
            </div>
            <br>
        <% end %>
    </div>

</main>